'use client'

import { startTransition, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import { ChevronDown, ChevronRight, Download, Scale } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

type Filters = { fechaDesde: string; fechaHasta: string; bancoId: string; procuradorId: string; estado: string; boleta: string; montoMin: string; montoMax: string; categories: string[]; groupBy: string }
type Row = { reciboId: string; numeroRecibo: string; rol: string; tribunal: string; caratula: string; gestion: string; estampoTemplate: string; procurador: string; banco: string; valor: number; estado: string; numeroBoleta: string; fechaEjecucion: string | null; fechaPago: string | null; category: string; categoryLabel: string }
type Group = { key: string; label: string; count: number; totalAmount: number; rows: Row[] }
type Report = { groups: Group[]; kpis: { total: number; reconciled: number; reconciliationPercentage: number; missingBoleta: number; pendingPayment: number; paidWithoutBoleta: number; totalAmount: number }; pagination: { page: number; totalPages: number; totalRows: number } }

const EMPTY: Filters = { fechaDesde: '', fechaHasta: '', bancoId: '', procuradorId: '', estado: '', boleta: '', montoMin: '', montoMax: '', categories: [], groupBy: 'category' }
const categoryOptions = [
  ['RECONCILED', 'Conciliado'], ['BOLETA_PENDING_PAYMENT', 'Boleta pendiente de pago'],
  ['PAID_WITHOUT_BOLETA', 'Pagado sin boleta'], ['WITHOUT_BOLETA_UNPAID', 'Sin boleta y sin pagar'],
]

function parse(params: URLSearchParams): Filters { return { fechaDesde: params.get('fechaEjecucionDesde') ?? '', fechaHasta: params.get('fechaEjecucionHasta') ?? '', bancoId: params.get('bancoId') ?? '', procuradorId: params.get('procuradorId') ?? '', estado: params.get('estado') ?? '', boleta: params.get('numeroBoleta') ?? '', montoMin: params.get('montoMin') ?? '', montoMax: params.get('montoMax') ?? '', categories: params.getAll('category'), groupBy: params.get('groupBy') ?? 'category' } }
function hasFilters(filters: Filters) { return !!(filters.fechaDesde || filters.fechaHasta || filters.bancoId || filters.procuradorId || filters.estado || filters.boleta || filters.montoMin || filters.montoMax || filters.categories.length) }
function query(filters: Filters, page = 1) { const p = new URLSearchParams(); if (filters.fechaDesde) p.set('fechaEjecucionDesde', filters.fechaDesde); if (filters.fechaHasta) p.set('fechaEjecucionHasta', filters.fechaHasta); if (filters.bancoId) p.set('bancoId', filters.bancoId); if (filters.procuradorId) p.set('procuradorId', filters.procuradorId); if (filters.estado) p.set('estado', filters.estado); if (filters.boleta) { p.set('numeroBoleta', filters.boleta); p.set('boletaMatch', 'contains') } if (filters.montoMin) p.set('montoMin', filters.montoMin); if (filters.montoMax) p.set('montoMax', filters.montoMax); filters.categories.forEach(value => p.append('category', value)); p.set('groupBy', filters.groupBy); p.set('page', String(page)); p.set('pageSize', '25'); return p }
function bodyFilters(filters: Filters) { return { procuradorIds: filters.procuradorId ? [filters.procuradorId] : [], bancoIds: filters.bancoId ? [filters.bancoId] : [], abogadoIds: [], estados: filters.estado ? [filters.estado] : [], estampoTemplates: [], fechaEjecucionDesde: filters.fechaDesde || undefined, fechaEjecucionHasta: filters.fechaHasta || undefined, numeroBoleta: filters.boleta || undefined, boletaMatch: 'contains', montoMin: filters.montoMin || undefined, montoMax: filters.montoMax || undefined, page: 1, pageSize: 25 } }
function money(value: number) { return new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(value) }
function date(value: string | null) { return value ? new Intl.DateTimeFormat('es-CL').format(new Date(value)) : '-' }

export default function ReconciliationPage() {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams()
  const appliedFilters = useMemo(() => parse(searchParams), [searchParams]); const applied = hasFilters(appliedFilters); const page = Number(searchParams.get('page') ?? 1) || 1
  const [filters, setFilters] = useState(appliedFilters); const [report, setReport] = useState<Report | null>(null)
  const [banks, setBanks] = useState<Array<{ id: number; nombre: string }>>([]); const [procuradores, setProcuradores] = useState<Array<{ id: number; nombre: string }>>([])
  const [expanded, setExpanded] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [exporting, setExporting] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { setFilters(appliedFilters) }, [appliedFilters])
  useEffect(() => { Promise.all([fetch('/api/bancos').then(r => r.json()), fetch('/api/procuradores').then(r => r.json())]).then(([b,p]) => { setBanks(b.data ?? []); setProcuradores(p.data ?? []) }).catch(() => setError('No se pudieron cargar los filtros.')) }, [])
  useEffect(() => {
    if (!applied) { setReport(null); return }
    let ignore = false; setLoading(true); setError(null)
    fetch(`/api/recibos/reconciliation?${searchParams}`).then(r => r.json()).then(payload => { if (!payload.ok) throw new Error(payload.error); if (!ignore) setReport(payload.data) }).catch(e => { if (!ignore) setError(e.message) }).finally(() => { if (!ignore) setLoading(false) })
    return () => { ignore = true }
  }, [applied, searchParams])
  const update = <K extends keyof Filters>(key: K, value: Filters[K]) => setFilters(current => ({ ...current, [key]: value }))
  const apply = (nextPage = 1) => { if (!hasFilters(filters)) { setError('Selecciona al menos un filtro para generar la conciliacion.'); return } startTransition(() => router.replace(`${pathname}?${query(filters, nextPage)}`)) }
  const clear = () => { setFilters(EMPTY); setReport(null); setError(null); startTransition(() => router.replace(pathname)) }
  const exportReport = async () => { if (!report) return; setExporting(true); try { const response = await fetch('/api/recibos/reconciliation/export', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ filters: bodyFilters(appliedFilters), categories: appliedFilters.categories, groupBy: appliedFilters.groupBy, filterSummary: searchParams.toString() }) }); if (!response.ok) throw new Error((await response.json()).error); const url = URL.createObjectURL(await response.blob()); const a = document.createElement('a'); a.href = url; a.download = 'conciliacion-recibos.xlsx'; a.click(); URL.revokeObjectURL(url) } catch (e) { setError(e instanceof Error ? e.message : 'Error al exportar.') } finally { setExporting(false) } }

  return <div className="app-shell"><div className="page-stack mx-auto max-w-[1700px] px-4 sm:px-6 lg:px-8">
    <section className="page-section overflow-visible">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="page-kicker">Recibos</div><h1 className="page-title">Conciliacion operativa</h1><p className="page-subtitle">Identifica recibos pagados, pendientes y sin boleta. Una regeneracion de la misma notificacion cuenta una sola vez.</p><div className="mt-4 flex gap-2"><Link href="/recibos" className="rounded-full border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Gestion</Link><Link href="/recibos/reconciliacion" className="rounded-full bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Conciliacion</Link></div></div><div className="flex gap-2"><Button variant="outline" onClick={clear}>Limpiar</Button><Button onClick={exportReport} disabled={!report || exporting}><Download className="mr-2 h-4 w-4" />{exporting ? 'Exportando...' : 'Exportar reporte'}</Button></div></div>
      <div className="mt-6 grid gap-4 rounded-2xl border border-slate-200 bg-slate-50/70 p-5 md:grid-cols-2 xl:grid-cols-4">
        <label className="space-y-2 text-sm"><span>Fecha ejecucion desde</span><Input type="date" value={filters.fechaDesde} onChange={e => update('fechaDesde', e.target.value)} /></label>
        <label className="space-y-2 text-sm"><span>Fecha ejecucion hasta</span><Input type="date" value={filters.fechaHasta} onChange={e => update('fechaHasta', e.target.value)} /></label>
        <label className="space-y-2 text-sm"><span>Banco</span><select className="h-10 w-full rounded-md border border-slate-300 bg-white px-3" value={filters.bancoId} onChange={e => update('bancoId', e.target.value)}><option value="">Todos</option>{banks.map(item => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label>
        <label className="space-y-2 text-sm"><span>Procurador</span><select className="h-10 w-full rounded-md border border-slate-300 bg-white px-3" value={filters.procuradorId} onChange={e => update('procuradorId', e.target.value)}><option value="">Todos</option>{procuradores.map(item => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label>
        <label className="space-y-2 text-sm"><span>Estado pago</span><select className="h-10 w-full rounded-md border border-slate-300 bg-white px-3" value={filters.estado} onChange={e => update('estado', e.target.value)}><option value="">Todos</option><option value="PAGADO">Pagado</option><option value="NO_PAGADO">Sin pagar</option></select></label>
        <label className="space-y-2 text-sm"><span>N° boleta</span><Input value={filters.boleta} onChange={e => update('boleta', e.target.value)} /></label>
        <label className="space-y-2 text-sm"><span>Monto minimo</span><Input type="number" min="0" value={filters.montoMin} onChange={e => update('montoMin', e.target.value)} /></label>
        <label className="space-y-2 text-sm"><span>Monto maximo</span><Input type="number" min="0" value={filters.montoMax} onChange={e => update('montoMax', e.target.value)} /></label>
        <div className="md:col-span-2 xl:col-span-3"><div className="mb-2 text-sm">Categorias</div><div className="flex flex-wrap gap-2">{categoryOptions.map(([value,label]) => <label key={value} className="flex items-center gap-2 rounded-full border border-slate-300 bg-white px-3 py-2 text-sm"><input type="checkbox" checked={filters.categories.includes(value)} onChange={() => update('categories', filters.categories.includes(value) ? filters.categories.filter(item => item !== value) : [...filters.categories, value])} />{label}</label>)}</div></div>
        <label className="space-y-2 text-sm"><span>Agrupar por</span><select className="h-10 w-full rounded-md border border-slate-300 bg-white px-3" value={filters.groupBy} onChange={e => update('groupBy', e.target.value)}><option value="category">Categoria</option><option value="bank">Banco</option><option value="procurador">Procurador</option><option value="executionMonth">Mes ejecucion</option><option value="boleta">Boleta</option></select></label>
        <div className="md:col-span-2 xl:col-span-4 flex justify-end"><Button onClick={() => apply()} disabled={!hasFilters(filters)}><Scale className="mr-2 h-4 w-4" />Generar conciliacion</Button></div>
      </div>{error && <div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}
    </section>
    {!applied ? <section className="page-section"><div className="flex min-h-64 flex-col items-center justify-center text-center"><Scale className="h-10 w-10 text-blue-700" /><h2 className="mt-4 text-xl font-semibold">Selecciona el alcance del reporte</h2><p className="mt-2 max-w-xl text-slate-600">La conciliacion se genera solo despues de aplicar filtros para mantener la consulta rapida y deliberada.</p></div></section> : <>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{report && [[report.kpis.total,'Recibos logicos'],[report.kpis.reconciled,'Conciliados'],[`${report.kpis.reconciliationPercentage}%`,'Tasa conciliacion'],[report.kpis.missingBoleta,'Sin boleta'],[report.kpis.pendingPayment,'Pendientes pago'],[money(report.kpis.totalAmount),'Monto total']].map(([value,label]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-2xl font-semibold text-slate-950">{value}</div><div className="mt-1 text-xs uppercase tracking-wide text-slate-500">{label}</div></div>)}</section>
      <section className="page-section"><div className="mb-4 text-sm font-semibold">{loading ? 'Generando conciliacion...' : `${report?.pagination.totalRows ?? 0} recibos logicos`}</div><div className="space-y-3">{report?.groups.map(group => { const open = expanded.includes(group.key); return <div key={group.key} className="overflow-hidden rounded-xl border border-slate-200"><button className="flex w-full items-center justify-between bg-slate-50 px-4 py-3 text-left" onClick={() => setExpanded(current => open ? current.filter(key => key !== group.key) : [...current, group.key])}><span className="flex items-center gap-2">{open ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}<strong>{group.label}</strong></span><span className="text-sm text-slate-600">{group.count} recibos · {money(group.totalAmount)}</span></button>{open && <div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500">{['Recibo','ROL','Caratula','Gestion','Procurador','Banco','Monto','Estado','Boleta','Ejecucion','Pago'].map(h => <th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{group.rows.map(row => <tr key={row.reciboId} className="border-t border-slate-100"><td className="px-3 py-2 font-semibold">{row.numeroRecibo}</td><td className="px-3 py-2">{row.rol}</td><td className="px-3 py-2">{row.caratula}</td><td className="px-3 py-2">{row.gestion}</td><td className="px-3 py-2">{row.procurador}</td><td className="px-3 py-2">{row.banco}</td><td className="px-3 py-2">{money(row.valor)}</td><td className="px-3 py-2">{row.estado}</td><td className="px-3 py-2">{row.numeroBoleta}</td><td className="px-3 py-2">{date(row.fechaEjecucion)}</td><td className="px-3 py-2">{date(row.fechaPago)}</td></tr>)}</tbody></table></div>}</div> })}</div>{report && report.pagination.totalPages > 1 && <div className="mt-5 flex items-center justify-between"><Button variant="outline" disabled={page <= 1} onClick={() => apply(page - 1)}>Anterior</Button><span className="text-sm">Pagina {page} de {report.pagination.totalPages}</span><Button variant="outline" disabled={page >= report.pagination.totalPages} onClick={() => apply(page + 1)}>Siguiente</Button></div>}</section>
    </>}
  </div></div>
}
