'use client'

import { ChevronDown, ChevronUp, Clipboard, Inbox, RefreshCw, RotateCcw, Send, X } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import PaginationBar from './PaginationBar'
import { authorizationLabel, EmptyBlock, ErrorBlock, formatBytes, formatDateTime, LoadingBlock, modeLabel, reportTypeLabel, selectClassName, StatusBadge, targetLabel } from './reportes-ui'
import type { DeliveryAttemptDetail, DeliveryAttemptSummary, Paged } from './reportes-types'

type Filters = { page: number; reportType: string; status: string; mode: string; target: string; dateFrom: string; dateTo: string }

type Props = {
  data: Paged<DeliveryAttemptSummary> | null
  loading: boolean
  error: string | null
  filters: Filters
  focusedReportId: string | null
  expandedAttemptId: string | null
  details: Record<string, DeliveryAttemptDetail>
  detailLoading: string | null
  busyAction: string | null
  onFilterChange: (key: keyof Filters, value: string | number) => void
  onRefresh: () => void
  onToggle: (attempt: DeliveryAttemptSummary) => void
  onRetry: (attempt: DeliveryAttemptSummary) => void
  onResend: (attempt: DeliveryAttemptSummary) => void
  onCopy: (value: string) => void
  onClearReport: () => void
}

const emptyPagination = { page: 1, limit: 25, total: 0, totalPages: 0 }

function AttemptActions({ attempt, expanded, busy, onToggle, onRetry, onResend }: { attempt: DeliveryAttemptSummary; expanded: boolean; busy: boolean; onToggle: () => void; onRetry: () => void; onResend: () => void }) {
  return <div className="flex flex-wrap gap-2"><button type="button" aria-expanded={expanded} aria-controls={`attempt-detail-${attempt.id}`} onClick={onToggle} className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-800">{expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}Detalle</button>{attempt.failedCount > 0 && <button type="button" onClick={onRetry} disabled={busy} className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-amber-200 bg-amber-50 px-3 text-xs font-semibold text-amber-900 disabled:opacity-50"><RotateCcw className="h-3.5 w-3.5" />Reintentar fallidos</button>}{attempt.report.currentVersion && <button type="button" onClick={onResend} disabled={busy} className="inline-flex h-9 items-center gap-1.5 rounded-xl bg-slate-950 px-3 text-xs font-semibold text-white disabled:opacity-50"><Send className="h-3.5 w-3.5" />Reenviar a todos</button>}</div>
}

function IdentityValue({ label, value }: { label: string; value: string | null }) {
  return <div className="min-w-0"><dt className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">{label}</dt><dd className="mt-1 break-all font-mono text-xs leading-5 text-slate-700">{value || '—'}</dd></div>
}

function AttemptDetailPanel({ attempt, loading, onCopy }: { attempt?: DeliveryAttemptDetail; loading: boolean; onCopy: (value: string) => void }) {
  if (loading || !attempt) return <LoadingBlock label="Cargando detalle de entrega…" />
  return <div className="space-y-5">
    <div className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-2 xl:grid-cols-4"><IdentityValue label="Proveedor" value={attempt.provider} /><IdentityValue label="Cuenta de origen" value={attempt.fromAccount} /><IdentityValue label="Intento padre" value={attempt.parentAttempt ? `Intento ${attempt.parentAttempt.attemptNumber} · ${attempt.parentAttempt.status}` : null} /><IdentityValue label="Reintentos hijos" value={attempt.retryAttempts.length ? attempt.retryAttempts.map(item => `#${item.attemptNumber}`).join(', ') : null} /></div>
    {attempt.errorMessage && <p className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{attempt.errorMessage}</p>}
    <div><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h4 className="font-semibold text-slate-950">Destinatarios registrados</h4><p className="mt-1 text-xs text-slate-500">Instantánea inmutable de autorización, archivo y resultado.</p></div>{attempt.reportVersion?.checksumSha256 && <Button size="sm" variant="outline" onClick={() => onCopy(attempt.reportVersion!.checksumSha256!)}><Clipboard className="mr-2 h-3.5 w-3.5" />Copiar checksum adjunto</Button>}</div>
      <div className="space-y-3">{attempt.recipients.map(recipient => <article key={recipient.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="break-all font-semibold text-slate-950">{recipient.email}</p><p className="mt-1 text-xs text-slate-500">{authorizationLabel(recipient.authorizationDecision)} · {recipient.attemptCount} intentos de proveedor</p></div><StatusBadge value={recipient.status} /></div><dl className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><IdentityValue label="Archivo" value={recipient.attachmentFilename} /><IdentityValue label="Tamaño" value={formatBytes(recipient.attachmentByteSize)} /><IdentityValue label="Enviado" value={formatDateTime(recipient.sentAt)} /><IdentityValue label="Completado" value={formatDateTime(recipient.completedAt)} /><IdentityValue label="Message ID" value={recipient.providerMessageId} /><IdentityValue label="Thread ID" value={recipient.providerThreadId} /><IdentityValue label="Internet Message ID" value={recipient.providerInternetMessageId} /><IdentityValue label="Checksum adjunto" value={recipient.attachmentSha256} /></dl>{recipient.errorMessage && <p className="mt-4 rounded-xl bg-rose-50 px-3 py-2 text-xs leading-5 text-rose-800">{recipient.errorMessage}</p>}</article>)}</div>
    </div>
  </div>
}

export default function DeliveriesSection(props: Props) {
  const attempts = props.data?.items ?? []
  return <section id="reports-panel-deliveries" role="tabpanel" aria-labelledby="reports-tab-deliveries" className="app-section overflow-hidden">
    <div className="border-b border-slate-200 bg-slate-50/70 px-5 py-5 sm:px-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="page-kicker">Cadena de custodia</div><h2 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">Historial de entregas</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">Cada intento conserva sus destinatarios, versión adjunta y resultado de proveedor.</p></div><Button size="sm" variant="outline" onClick={props.onRefresh} disabled={props.loading}><RefreshCw className={`mr-2 h-4 w-4 ${props.loading ? 'animate-spin' : ''}`} />Actualizar</Button></div>
      {props.focusedReportId && <div className="mt-4 inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-800">Mostrando el reporte seleccionado<button type="button" onClick={props.onClearReport} aria-label="Mostrar entregas de todos los reportes" className="rounded-full p-1 hover:bg-blue-100"><X className="h-3.5 w-3.5" /></button></div>}
      <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><label className="space-y-1 text-xs font-semibold text-slate-600">Tipo<select className={`${selectClassName} w-full`} value={props.filters.reportType} onChange={event => props.onFilterChange('reportType', event.target.value)}><option value="all">Todos</option><option value="daily">Diarios</option><option value="monthly">Mensuales</option><option value="custom">Personalizados</option></select></label><label className="space-y-1 text-xs font-semibold text-slate-600">Estado<select className={`${selectClassName} w-full`} value={props.filters.status} onChange={event => props.onFilterChange('status', event.target.value)}><option value="all">Todos</option><option value="SENT">Enviados</option><option value="PARTIAL">Parciales</option><option value="FAILED">Fallidos</option><option value="PENDING">Pendientes</option><option value="SENDING">Enviando</option><option value="NO_RECIPIENTS">Sin destinatarios</option><option value="CANCELLED">Cancelados</option></select></label><label className="space-y-1 text-xs font-semibold text-slate-600">Origen<select className={`${selectClassName} w-full`} value={props.filters.mode} onChange={event => props.onFilterChange('mode', event.target.value)}><option value="all">Todos</option><option value="MANUAL">Manual</option><option value="SCHEDULED">Programado</option></select></label><label className="space-y-1 text-xs font-semibold text-slate-600">Objetivo<select className={`${selectClassName} w-full`} value={props.filters.target} onChange={event => props.onFilterChange('target', event.target.value)}><option value="all">Todos</option><option value="ALL_AUTHORIZED">Todos autorizados</option><option value="FAILED_ONLY">Solo fallidos</option></select></label><label className="space-y-1 text-xs font-semibold text-slate-600">Desde<Input type="date" value={props.filters.dateFrom} onChange={event => props.onFilterChange('dateFrom', event.target.value)} /></label><label className="space-y-1 text-xs font-semibold text-slate-600">Hasta<Input type="date" value={props.filters.dateTo} onChange={event => props.onFilterChange('dateTo', event.target.value)} /></label></div>
    </div>
    <div className="p-4 sm:p-6">{props.error ? <ErrorBlock message={props.error} onRetry={props.onRefresh} /> : props.loading && !props.data ? <LoadingBlock label="Cargando historial de entregas…" /> : !attempts.length ? <EmptyBlock icon={<Inbox className="h-6 w-6" />} title="No hay entregas para estos filtros" copy="Cambia el periodo o envía un reporte para iniciar esta trazabilidad." /> : <>
      <div className="space-y-3 xl:hidden">{attempts.map(attempt => { const expanded = props.expandedAttemptId === attempt.id; return <article key={attempt.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{reportTypeLabel(attempt.report.reportType)} · {attempt.report.periodDate}</p><h3 className="mt-1 text-lg font-semibold text-slate-950">Intento {attempt.attemptNumber}</h3></div><StatusBadge value={attempt.status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-slate-500">Versión adjunta</dt><dd className="mt-1 font-semibold">v{attempt.reportVersion?.versionNumber ?? '—'}</dd></div><div><dt className="text-xs text-slate-500">Origen</dt><dd className="mt-1 font-semibold">{modeLabel(attempt.mode)}</dd></div><div><dt className="text-xs text-slate-500">Resultados</dt><dd className="mt-1">{attempt.sentCount} enviados · {attempt.failedCount} fallidos</dd></div><div><dt className="text-xs text-slate-500">Creado</dt><dd className="mt-1">{formatDateTime(attempt.createdAt)}</dd></div></dl><div className="mt-4"><AttemptActions attempt={attempt} expanded={expanded} busy={!!props.busyAction} onToggle={() => props.onToggle(attempt)} onRetry={() => props.onRetry(attempt)} onResend={() => props.onResend(attempt)} /></div>{expanded && <div id={`attempt-detail-${attempt.id}`} className="mt-5 border-t border-slate-200 pt-5"><AttemptDetailPanel attempt={props.details[attempt.id]} loading={props.detailLoading === attempt.id} onCopy={props.onCopy} /></div>}</article> })}</div>
      <div className="hidden overflow-x-auto rounded-2xl border border-slate-200 xl:block"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-slate-100/80 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Intento</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Origen</th><th className="px-4 py-3">Versión fijada</th><th className="px-4 py-3">Resultados</th><th className="px-4 py-3">Solicitado</th><th className="px-4 py-3">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{attempts.map(attempt => { const expanded = props.expandedAttemptId === attempt.id; return [<tr key={attempt.id} className="align-top hover:bg-slate-50/70"><td className="px-4 py-4"><div className="font-semibold text-slate-950">Intento {attempt.attemptNumber}</div><div className="mt-1 text-xs text-slate-500">{reportTypeLabel(attempt.report.reportType)} · {attempt.report.periodDate}</div>{attempt.parentAttempt && <div className="mt-1 text-xs text-blue-700">Reintento de #{attempt.parentAttempt.attemptNumber}</div>}</td><td className="px-4 py-4"><StatusBadge value={attempt.status} /><div className="mt-2 text-xs text-slate-500">{targetLabel(attempt.target)}</div></td><td className="px-4 py-4 text-xs text-slate-600"><div className="font-semibold text-slate-800">{modeLabel(attempt.mode)}</div><div className="mt-1">{attempt.requestedBy?.email ?? 'Sistema'}</div></td><td className="px-4 py-4"><div className="font-semibold">v{attempt.reportVersion?.versionNumber ?? '—'}</div><div className="mt-1 max-w-44 truncate text-xs text-slate-500" title={attempt.reportVersion?.fileName}>{attempt.reportVersion?.fileName ?? 'Archivo no disponible'}</div></td><td className="px-4 py-4 text-xs leading-5 text-slate-600"><span className="font-semibold text-emerald-700">{attempt.sentCount} enviados</span><br /><span className="font-semibold text-rose-700">{attempt.failedCount} fallidos</span><br />{attempt.skippedCount} omitidos</td><td className="px-4 py-4 text-xs text-slate-600">{formatDateTime(attempt.createdAt)}<div className="mt-1">{attempt.retryCount} reintentos hijos</div></td><td className="px-4 py-4"><AttemptActions attempt={attempt} expanded={expanded} busy={!!props.busyAction} onToggle={() => props.onToggle(attempt)} onRetry={() => props.onRetry(attempt)} onResend={() => props.onResend(attempt)} /></td></tr>, expanded ? <tr key={`${attempt.id}-detail`}><td id={`attempt-detail-${attempt.id}`} colSpan={7} className="bg-slate-50 px-5 py-5"><AttemptDetailPanel attempt={props.details[attempt.id]} loading={props.detailLoading === attempt.id} onCopy={props.onCopy} /></td></tr> : null] })}</tbody></table></div>
    </>}</div>
    <PaginationBar pagination={props.data?.pagination ?? emptyPagination} loading={props.loading} noun="intento" onPageChange={page => props.onFilterChange('page', page)} />
  </section>
}
