'use client'

import { Ban, ChevronDown, ChevronUp, ListRestart, ListTodo, RefreshCw } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { usePathname, useRouter, useSearchParams } from 'next/navigation'

import { Button } from '@/components/ui/button'
import PaginationBar from './PaginationBar'
import { EmptyBlock, ErrorBlock, formatDateTime, LoadingBlock, reportTypeLabel, selectClassName, StatusBadge } from './reportes-ui'
import type { JobEnvelope, ReportJobRow } from './reportes-types'

type JobDetail = ReportJobRow & { runs: Array<{ id: string; attemptNumber: number; outcome: string; startedAt: string; completedAt: string | null; safeError: string | null }>; retryOfJob?: { id: string; status: string } | null; retryJobs: Array<{ id: string; status: string; createdAt: string }> }

async function request<T>(url: string, init?: RequestInit) {
  const response = await fetch(url, { credentials: 'include', cache: 'no-store', ...init })
  const payload = await response.json().catch(() => ({}))
  if (!response.ok || !payload.ok) throw new Error(payload.error?.message ?? 'No se pudo completar la operación.')
  return payload.data as T
}

function progress(job: ReportJobRow) { return Math.max(0, Math.min(100, Math.round((job.completedUnits / Math.max(job.totalUnits, 1)) * 100))) }

export default function JobsSection({ onMessage }: { onMessage: (value: string, error?: boolean) => void }) {
  const searchParams = useSearchParams(); const router = useRouter(); const pathname = usePathname()
  const page = Math.max(1, Number(searchParams.get('jobPage')) || 1)
  const status = searchParams.get('jobStatus') ?? 'all'; const type = searchParams.get('jobType') ?? 'all'; const reportKind = searchParams.get('jobKind') ?? 'all'; const origin = searchParams.get('jobOrigin') ?? 'all'
  const [data, setData] = useState<JobEnvelope | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [refresh, setRefresh] = useState(0)
  const [expanded, setExpanded] = useState<string | null>(null); const [details, setDetails] = useState<Record<string, JobDetail>>({}); const [busy, setBusy] = useState<string | null>(null)
  const query = useMemo(() => new URLSearchParams({ page: String(page), limit: '25', status, type, reportKind, origin }).toString(), [origin, page, reportKind, status, type])
  const active = data?.items.some(job => ['QUEUED', 'RUNNING', 'CANCEL_REQUESTED'].includes(job.status))
  const load = useCallback((signal?: AbortSignal) => { setLoading(true); setError(null); return request<JobEnvelope>(`/api/reports/jobs?${query}`, { signal }).then(setData).catch(value => { if (value.name !== 'AbortError') setError(value.message) }).finally(() => { if (!signal?.aborted) setLoading(false) }) }, [query])
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort() }, [load, refresh])
  useEffect(() => { if (!active) return; const interval = window.setInterval(() => { void load() }, 4000); return () => window.clearInterval(interval) }, [active, load])
  const update = (values: Record<string, string | number | null>) => { const next = new URLSearchParams(searchParams.toString()); Object.entries(values).forEach(([key, value]) => value === null || value === '' || value === 'all' || (key === 'jobPage' && value === 1) ? next.delete(key) : next.set(key, String(value))); router.replace(`${pathname}?${next}`, { scroll: false }) }
  const toggle = async (job: ReportJobRow) => { if (expanded === job.id) return setExpanded(null); setExpanded(job.id); if (!details[job.id]) try { const detail = await request<JobDetail>(`/api/reports/jobs/${job.id}`); setDetails(current => ({ ...current, [job.id]: detail })) } catch (value) { onMessage(value instanceof Error ? value.message : 'No se pudo cargar el trabajo.', true) } }
  const action = async (job: ReportJobRow, kind: 'cancel' | 'retry') => { setBusy(`${kind}:${job.id}`); try { await request(`/api/reports/jobs/${job.id}/${kind}`, { method: 'POST', headers: { 'Idempotency-Key': `report-job-${kind}-${crypto.randomUUID()}` } }); onMessage(kind === 'cancel' ? 'Se solicitó la cancelación del trabajo.' : 'El reintento quedó en cola.'); setRefresh(value => value + 1) } catch (value) { onMessage(value instanceof Error ? value.message : 'No se pudo completar la acción.', true) } finally { setBusy(null) } }
  const rows = data?.items ?? []
  const detailPanel = (job: ReportJobRow) => { const detail = details[job.id]; return <div className="grid gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 lg:grid-cols-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Progreso durable</p><p className="mt-2 text-sm font-semibold text-slate-900">{job.progressPhase} · {progress(job)}%</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-600 transition-all" style={{ width: `${progress(job)}%` }} /></div><p className="mt-2 text-xs text-slate-500">Lease: {formatDateTime(job.leaseExpiresAt)}</p></div><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Intentos de ejecución</p><div className="mt-2 space-y-2">{detail?.runs?.map(run => <div key={run.id} className="text-xs text-slate-600"><b>#{run.attemptNumber}</b> · {run.outcome} · {formatDateTime(run.startedAt)}{run.safeError && <p className="mt-1 text-rose-700">{run.safeError}</p>}</div>) ?? <span className="text-xs text-slate-500">Cargando…</span>}</div></div><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Linaje</p><p className="mt-2 text-xs text-slate-600">{detail?.retryOfJob ? `Reintento de ${detail.retryOfJob.id}` : 'Trabajo original'} · {detail?.retryJobs?.length ?? 0} reintentos hijos</p>{job.safeError && <p className="mt-3 rounded-xl border border-rose-100 bg-rose-50 p-2 text-xs text-rose-800">{job.safeError}</p>}</div></div> }
  return <section id="operations-panel-jobs" role="tabpanel" aria-labelledby="operations-view-jobs" className="app-section overflow-hidden">
    <header className="border-b border-slate-200 bg-slate-50/70 p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="page-kicker">Cola durable</div><h2 className="mt-2 text-2xl font-semibold text-slate-950">Trabajos</h2><p className="mt-1 text-sm text-slate-600">Generación y entrega con leases, progreso, intentos y cancelación cooperativa.</p></div><Button variant="outline" onClick={() => setRefresh(value => value + 1)}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Actualizar</Button></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-semibold text-slate-600">Estado<select className={`${selectClassName} mt-1 w-full`} value={status} onChange={event => update({ jobStatus: event.target.value, jobPage: 1 })}><option value="all">Todos</option>{['QUEUED','RUNNING','CANCEL_REQUESTED','SUCCEEDED','FAILED','CANCELLED'].map(value => <option key={value}>{value}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Tipo<select className={`${selectClassName} mt-1 w-full`} value={type} onChange={event => update({ jobType: event.target.value, jobPage: 1 })}><option value="all">Todos</option><option value="GENERATE">Generación</option><option value="DELIVER">Entrega</option></select></label><label className="text-xs font-semibold text-slate-600">Reporte<select className={`${selectClassName} mt-1 w-full`} value={reportKind} onChange={event => update({ jobKind: event.target.value, jobPage: 1 })}><option value="all">Todos</option><option value="daily">Diario</option><option value="monthly">Mensual</option><option value="custom">Personalizado</option></select></label><label className="text-xs font-semibold text-slate-600">Origen<select className={`${selectClassName} mt-1 w-full`} value={origin} onChange={event => update({ jobOrigin: event.target.value, jobPage: 1 })}><option value="all">Todos</option><option value="MANUAL">Manual</option><option value="SCHEDULED">Programado</option><option value="CHAINED">Encadenado</option></select></label></div>
    </header>
    <div className="p-4 sm:p-6">{error ? <ErrorBlock message={error} onRetry={() => setRefresh(value => value + 1)} /> : loading && !data ? <LoadingBlock label="Cargando trabajos…" /> : !rows.length ? <EmptyBlock icon={<ListTodo className="h-6 w-6" />} title="No hay trabajos" copy="Las generaciones y entregas aparecerán aquí al ser encoladas." /> : <div className="space-y-3">{rows.map(job => <article key={job.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><StatusBadge value={job.status} /><span className="text-xs font-semibold uppercase tracking-wider text-slate-500">{job.type === 'GENERATE' ? 'Generación' : 'Entrega'} · {reportTypeLabel(job.reportKind)}</span></div><h3 className="mt-2 truncate text-lg font-semibold text-slate-950">{job.customDefinition?.name ?? job.requestedPeriodLabel}</h3><p className="mt-1 text-xs text-slate-500">{job.origin} · {formatDateTime(job.createdAt)} · intento {job.attemptCount}/{job.maxAttempts}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => toggle(job)} className="inline-flex h-9 items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-semibold">{expanded === job.id ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}Detalle</button>{['QUEUED','RUNNING','CANCEL_REQUESTED'].includes(job.status) && <button type="button" disabled={!!busy || job.status === 'CANCEL_REQUESTED'} onClick={() => action(job, 'cancel')} className="inline-flex h-9 items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 text-xs font-semibold text-amber-900 disabled:opacity-50"><Ban className="h-4 w-4" />Cancelar</button>}{['FAILED','CANCELLED'].includes(job.status) && <button type="button" disabled={!!busy} onClick={() => action(job, 'retry')} className="inline-flex h-9 items-center gap-2 rounded-xl bg-slate-950 px-3 text-xs font-semibold text-white disabled:opacity-50"><ListRestart className="h-4 w-4" />Reintentar</button>}</div></div>{expanded === job.id && <div className="mt-4">{detailPanel(job)}</div>}</article>)}</div>}</div>
    <PaginationBar pagination={data?.pagination ?? { page: 1, limit: 25, total: 0, totalPages: 0 }} noun="trabajo" loading={loading} onPageChange={value => update({ jobPage: value })} />
  </section>
}
