'use client'

import { AlertTriangle, Save, UsersRound } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'

import { Button } from '@/components/ui/button'
import { EmptyBlock, ErrorBlock, LoadingBlock } from './reportes-ui'
import type { RecipientConfiguration } from './reportes-types'

async function request<T>(url: string, init?: RequestInit) {
  const response = await fetch(url, { credentials: 'include', cache: 'no-store', ...init }); const payload = await response.json().catch(() => ({}))
  if (!response.ok || !payload.ok) throw new Error(payload.error?.message ?? 'No se pudo completar la operación.')
  return payload.data as T
}

export default function RecipientsSection({ onMessage }: { onMessage: (value: string, error?: boolean) => void }) {
  const [data, setData] = useState<RecipientConfiguration | null>(null); const [draft, setDraft] = useState<RecipientConfiguration['recipients']>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  const load = () => { setLoading(true); setError(null); request<RecipientConfiguration>('/api/reports/recipients').then(value => { setData(value); setDraft(value.recipients) }).catch(value => setError(value.message)).finally(() => setLoading(false)) }
  useEffect(load, [])
  const dirty = useMemo(() => !!data && JSON.stringify(data.recipients) !== JSON.stringify(draft), [data, draft])
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = '' } }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler) }, [dirty])
  const counts = draft.reduce((value, row) => ({ daily: value.daily + Number(row.active && row.dailyEnabled), monthly: value.monthly + Number(row.active && row.monthlyEnabled), custom: value.custom + Number(row.active && row.customEnabled) }), { daily: 0, monthly: 0, custom: 0 })
  const toggle = (userId: string, field: 'dailyEnabled' | 'monthlyEnabled' | 'customEnabled') => {
    const current = draft.find(row => row.userId === userId); if (!current) return
    if (current[field] && draft.filter(row => row.active && row[field]).length === 1 && !window.confirm('Esta acción dejará el tipo de reporte sin destinatarios elegibles. ¿Deseas continuar?')) return
    setDraft(rows => rows.map(row => row.userId === userId ? { ...row, [field]: !row[field] } : row))
  }
  const save = async () => { if (!data) return; setSaving(true); try { const saved = await request<RecipientConfiguration>('/api/reports/recipients', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ revision: data.revision, recipients: draft.filter(row => row.active).map(({ userId, dailyEnabled, monthlyEnabled, customEnabled }) => ({ userId, dailyEnabled, monthlyEnabled, customEnabled })) }) }); setData(saved); setDraft(saved.recipients); onMessage('Configuración de destinatarios guardada.') } catch (value) { onMessage(value instanceof Error ? value.message : 'No se pudo guardar.', true); if (value instanceof Error && /otra sesión/i.test(value.message)) load() } finally { setSaving(false) } }
  return <section id="operations-panel-recipients" role="tabpanel" aria-labelledby="operations-view-recipients" className="app-section overflow-hidden">
    <header className="border-b border-slate-200 bg-slate-50/70 p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="page-kicker">Matriz autorizada</div><h2 className="mt-2 text-2xl font-semibold text-slate-950">Destinatarios</h2><p className="mt-1 text-sm text-slate-600">Solo administradores activos de esta oficina. La autorización se vuelve a validar justo antes de cada envío.</p></div><Button onClick={save} disabled={!dirty || saving}><Save className="mr-2 h-4 w-4" />{saving ? 'Guardando…' : 'Guardar cambios'}</Button></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className={`rounded-2xl border p-3 ${counts.daily ? 'border-blue-100 bg-blue-50' : 'border-amber-200 bg-amber-50'}`}><p className="text-xs font-semibold text-slate-600">Diarios</p><p className="mt-1 text-2xl font-semibold">{counts.daily}</p></div><div className={`rounded-2xl border p-3 ${counts.monthly ? 'border-cyan-100 bg-cyan-50' : 'border-amber-200 bg-amber-50'}`}><p className="text-xs font-semibold text-slate-600">Mensuales</p><p className="mt-1 text-2xl font-semibold">{counts.monthly}</p></div><div className={`rounded-2xl border p-3 ${counts.custom ? 'border-violet-100 bg-violet-50' : 'border-amber-200 bg-amber-50'}`}><p className="text-xs font-semibold text-slate-600">Personalizados</p><p className="mt-1 text-2xl font-semibold">{counts.custom}</p></div></div>
      {(!counts.daily || !counts.monthly || !counts.custom) && <p role="status" className="mt-4 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-900"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />Los tipos sin destinatarios fallarán de forma segura con NO_RECIPIENTS y sus programaciones mostrarán atención.</p>}
    </header>
    <div className="p-4 sm:p-6">{error ? <ErrorBlock message={error} onRetry={load} /> : loading ? <LoadingBlock label="Cargando destinatarios…" /> : !draft.length ? <EmptyBlock icon={<UsersRound className="h-6 w-6" />} title="No hay administradores configurables" copy="Activa un administrador de la oficina antes de configurar reportes." /> : <><div className="space-y-3 md:hidden">{draft.map(row => <article key={row.userId} className={`rounded-2xl border p-4 ${row.active ? 'border-slate-200 bg-white' : 'border-slate-200 bg-slate-50 opacity-70'}`}><p className="break-all font-semibold text-slate-950">{row.email}</p><p className="mt-1 text-xs text-slate-500">{row.active ? 'Administrador activo' : 'Administrador inactivo'}</p><div className="mt-4 grid grid-cols-3 gap-2">{([['dailyEnabled','Diario'],['monthlyEnabled','Mensual'],['customEnabled','Personalizado']] as const).map(([field,label]) => <label key={field} className="flex flex-col items-center gap-2 rounded-xl border border-slate-200 p-2 text-[11px] font-semibold"><input type="checkbox" checked={row[field]} disabled={!row.active} onChange={() => toggle(row.userId, field)} className="h-4 w-4 accent-blue-600" />{label}</label>)}</div></article>)}</div><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 md:block"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-100 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Administrador</th><th className="px-4 py-3 text-center">Diario</th><th className="px-4 py-3 text-center">Mensual</th><th className="px-4 py-3 text-center">Personalizado</th><th className="px-4 py-3">Estado</th></tr></thead><tbody className="divide-y divide-slate-100">{draft.map(row => <tr key={row.userId} className={!row.active ? 'bg-slate-50 text-slate-400' : ''}><td className="max-w-sm break-all px-4 py-4 font-semibold">{row.email}</td>{(['dailyEnabled','monthlyEnabled','customEnabled'] as const).map(field => <td key={field} className="px-4 py-4 text-center"><input aria-label={`${field} para ${row.email}`} type="checkbox" checked={row[field]} disabled={!row.active} onChange={() => toggle(row.userId, field)} className="h-4 w-4 accent-blue-600" /></td>)}<td className="px-4 py-4 text-xs">{row.active ? 'Activo' : 'Inactivo'}</td></tr>)}</tbody></table></div></>}</div>
    {dirty && <div role="status" className="border-t border-amber-200 bg-amber-50 px-5 py-3 text-xs font-semibold text-amber-900">Hay cambios sin guardar. Revisión actual: {data?.revision}.</div>}
  </section>
}
