'use client'

import { CalendarClock, Play, RefreshCw, Save } from 'lucide-react'
import { useEffect, useState } from 'react'

import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { EmptyBlock, ErrorBlock, formatDateTime, LoadingBlock, StatusBadge } from './reportes-ui'
import type { ReportScheduleRow } from './reportes-types'

async function request<T>(url: string, init?: RequestInit) { const response = await fetch(url, { credentials: 'include', cache: 'no-store', ...init }); const payload = await response.json().catch(() => ({})); if (!response.ok || !payload.ok) throw new Error(payload.error?.message ?? 'No se pudo completar la operación.'); return payload.data as T }

function scheduleName(schedule: ReportScheduleRow) { return schedule.customDefinition?.name ?? (schedule.kind === 'DAILY' ? 'Reporte diario estándar' : 'Reporte mensual estándar') }

export default function SchedulesSection({ onMessage }: { onMessage: (value: string, error?: boolean) => void }) {
  const [rows, setRows] = useState<ReportScheduleRow[]>([]); const [drafts, setDrafts] = useState<Record<string, Partial<ReportScheduleRow>>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null)
  const load = () => { setLoading(true); setError(null); request<ReportScheduleRow[]>('/api/reports/schedules').then(value => { setRows(value); setDrafts({}) }).catch(value => setError(value.message)).finally(() => setLoading(false)) }
  useEffect(load, [])
  const change = (id: string, value: Partial<ReportScheduleRow>) => setDrafts(current => ({ ...current, [id]: { ...current[id], ...value } }))
  const save = async (schedule: ReportScheduleRow) => { const draft = drafts[schedule.id]; if (!draft) return; const enabling = draft.enabled === true && !schedule.enabled; if (enabling && !window.confirm(`Se habilitará ${scheduleName(schedule)} para ${schedule.recipientCount} destinatarios. La próxima ejecución se calculará en horario de Chile. ¿Continuar?`)) return; setBusy(`save:${schedule.id}`); try { await request(`/api/reports/schedules/${schedule.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ enabled: draft.enabled ?? schedule.enabled, localTime: draft.localTime ?? schedule.localTime, weekday: draft.weekday ?? schedule.weekday, monthDay: draft.monthDay ?? schedule.monthDay, latenessThresholdMinutes: Number(draft.latenessThresholdMinutes ?? schedule.latenessThresholdMinutes) }) }); onMessage('Programación actualizada.'); load() } catch (value) { onMessage(value instanceof Error ? value.message : 'No se pudo guardar.', true) } finally { setBusy(null) } }
  const runNow = async (schedule: ReportScheduleRow) => { if (!window.confirm(`Se encolará una ejecución inmediata de ${scheduleName(schedule)} para el último periodo completado. ¿Continuar?`)) return; setBusy(`run:${schedule.id}`); try { await request(`/api/reports/schedules/${schedule.id}/run-now`, { method: 'POST', headers: { 'Idempotency-Key': `report-schedule-run-${crypto.randomUUID()}` } }); onMessage('La ejecución inmediata quedó en cola.'); load() } catch (value) { onMessage(value instanceof Error ? value.message : 'No se pudo ejecutar.', true) } finally { setBusy(null) } }
  return <section id="operations-panel-schedules" role="tabpanel" aria-labelledby="operations-view-schedules" className="app-section overflow-hidden"><header className="border-b border-slate-200 bg-slate-50/70 p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="page-kicker">Reloj Chile · America/Santiago</div><h2 className="mt-2 text-2xl font-semibold text-slate-950">Programación y salud</h2><p className="mt-1 text-sm text-slate-600">Horarios resueltos con DST, umbral de atraso y ejecución idempotente.</p></div><Button variant="outline" onClick={load}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Actualizar</Button></div></header>
    <div className="p-4 sm:p-6">{error ? <ErrorBlock message={error} onRetry={load} /> : loading ? <LoadingBlock label="Cargando programaciones…" /> : !rows.length ? <EmptyBlock icon={<CalendarClock className="h-6 w-6" />} title="No hay programaciones" copy="Crea una definición personalizada o actualiza los horarios estándar." /> : <div className="grid gap-4 xl:grid-cols-2">{rows.map(schedule => { const draft = drafts[schedule.id] ?? {}; const enabled = draft.enabled ?? schedule.enabled; return <article key={schedule.id} className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{schedule.frequency} · {schedule.recipientCount} destinatarios</p><h3 className="mt-1 text-lg font-semibold text-slate-950">{scheduleName(schedule)}</h3></div><StatusBadge value={schedule.health.state} /></div><p className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-600">{schedule.health.reason}</p>
      <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Hora Chile<Input className="mt-1" type="time" value={String(draft.localTime ?? schedule.localTime)} onChange={event => change(schedule.id, { localTime: event.target.value })} /></label>{schedule.frequency === 'WEEKLY' && <label className="text-xs font-semibold text-slate-600">Día semanal<select className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3" value={Number(draft.weekday ?? schedule.weekday ?? 1)} onChange={event => change(schedule.id, { weekday: Number(event.target.value) })}>{['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'].map((label,index) => <option key={label} value={index+1}>{label}</option>)}</select></label>}{schedule.frequency === 'MONTHLY' && <label className="text-xs font-semibold text-slate-600">Día del mes<Input className="mt-1" type="number" min={1} max={28} value={Number(draft.monthDay ?? schedule.monthDay ?? 1)} onChange={event => change(schedule.id, { monthDay: Number(event.target.value) })} /></label>}<label className="text-xs font-semibold text-slate-600">Umbral de atraso (min)<Input className="mt-1" type="number" min={5} max={1440} value={Number(draft.latenessThresholdMinutes ?? schedule.latenessThresholdMinutes)} onChange={event => change(schedule.id, { latenessThresholdMinutes: Number(event.target.value) })} /></label><label className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold"><input type="checkbox" checked={enabled} onChange={event => change(schedule.id, { enabled: event.target.checked })} className="h-4 w-4 accent-blue-600" />Programación habilitada</label></div>
      <dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-500">Próxima ejecución</dt><dd className="mt-1 font-semibold">{formatDateTime(schedule.nextRunAt)}</dd></div><div><dt className="text-slate-500">Último éxito</dt><dd className="mt-1 font-semibold">{formatDateTime(schedule.lastSuccessAt)}</dd></div><div><dt className="text-slate-500">Último fallo</dt><dd className="mt-1 font-semibold">{formatDateTime(schedule.lastFailureAt)}</dd></div><div><dt className="text-slate-500">Fallos consecutivos</dt><dd className="mt-1 font-semibold">{schedule.consecutiveFailures}</dd></div></dl>{schedule.safeLastError && <p className="mt-3 rounded-xl border border-rose-100 bg-rose-50 p-2 text-xs text-rose-800">{schedule.safeLastError}</p>}<div className="mt-5 flex flex-wrap gap-2"><Button size="sm" disabled={!drafts[schedule.id] || !!busy} onClick={() => save(schedule)}><Save className="mr-2 h-4 w-4" />Guardar</Button><Button size="sm" variant="outline" disabled={!!busy} onClick={() => runNow(schedule)}><Play className="mr-2 h-4 w-4" />Ejecutar ahora</Button></div></article> })}</div>}</div>
  </section>
}
