import type { EstampoBaseSeed } from './types'

export const busquedasNegativasSeeds: EstampoBaseSeed[] = [
  {
    slug: 'busqueda_negativa_direccion_incompleta',
    nombreVisible: 'Dirección señalada se encuentra incompleta',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion: 'Búsqueda negativa cuando la dirección informada por la parte está incompleta.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en el domicilio ubicado en $direccion_ejecutado, siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente, diligencia que no pude efectuar por cuanto, la dirección señalada se encuentra incompleta. En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      'Drs $monto_ejecutado',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      // 3.1 Auto-filled variables
      {
        name: 'direccion_ejecutado',
        label: 'Dirección del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      // 3.2 Wizard + derived
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandadX)',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
    ],
  },
  {
    slug: 'busqueda_negativa_falta_numero_casa',
    nombreVisible: 'Falta especificar número de casa',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion:
      'Búsqueda negativa cuando la dirección indicada no tiene numeración o falta el número de casa del inmueble.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en el domicilio ubicado en $direccion_ejecutado, siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente, diligencia que no pude realizar, por cuanto, no existe la numeración $numero_casa en la dirección señalada. En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      'Drs $monto_ejecutado',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      // 3.1 Auto-filled variables
      {
        name: 'direccion_ejecutado',
        label: 'Dirección del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      // 3.2 Wizard + derived
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandado(a))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'numero_casa',
        label: 'Numeración (número de casa) indicada en la dirección',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        order: 2,
        variable: 'numero_casa',
        text: 'Numeración (número de casa) indicada en la dirección',
        inputType: 'TEXT',
      },
    ],
  },
  {
    slug: 'busqueda_negativa_falta_especificar_numero_casa_inmueble',
    nombreVisible: 'Falta especificar número de casa del inmueble señalado',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion: 'Búsqueda negativa cuando falta especificar el número de casa del inmueble señalado.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en $direccion_ejecutado, siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente, diligencia que no pude realizar por cuanto, falta especificar el número de casa del inmueble señalado. En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      'Drs $monto_ejecutado',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      // 3.1 Auto-filled variables
      {
        name: 'direccion_ejecutado',
        label: 'Dirección del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      // 3.2 Wizard + derived
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandado(a))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
    ],
  },
  {
    slug: 'busqueda_negativa_inmueble_desocupado_sin_moradores',
    nombreVisible: 'Inmueble desocupado y sin moradores',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion: 'Búsqueda negativa cuando el inmueble se encuentra desocupado y sin moradores.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en el domicilio ubicado en $direccion_ejecutado, siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente, diligencia que no pude efectuar por cuanto, el inmueble se encuentra desocupado y sin moradores. En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      'Drs $monto_ejecutado',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      // 3.1 Auto-filled variables
      {
        name: 'direccion_ejecutado',
        label: 'Dirección del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      // 3.2 Wizard + derived
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandado(a))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
    ],
  },
  {
    slug: 'busqueda_negativa_no_existe_la_numeracion',
    nombreVisible: 'No existe la numeración',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion: 'Búsqueda negativa cuando no existe la numeración indicada en la dirección señalada.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en el domicilio ubicado en $direccion_ejecutado, siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente, diligencia que no pude realizar, por cuanto no existe la numeración $numero_casa en la dirección señalada. En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      'Drs $monto_ejecutado',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      // 3.1 Auto-filled variables
      {
        name: 'direccion_ejecutado',
        label: 'Dirección del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      // 3.2 Wizard + derived
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandado(a))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'numero_casa',
        label: 'Numeración (número de casa) indicada en la dirección',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        order: 2,
        variable: 'numero_casa',
        text: 'Numeración (número de casa) indicada en la dirección',
        inputType: 'TEXT',
      },
    ],
  },
  {
    slug: 'busqueda_negativa_no_existe_calle_en_comuna',
    nombreVisible: 'No existe la calle en esta comuna',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion: 'Búsqueda negativa cuando la calle indicada no existe en la comuna.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en el domicilio ubicado en $direccion_ejecutado, siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente, diligencia que no pude realizar, por cuanto la calle $nombre_calle_inexistente no existe en la comuna. En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      'Drs $monto_ejecutado',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      // 3.1 Auto-filled variables
      {
        name: 'direccion_ejecutado',
        label: 'Dirección del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      // 3.2 Wizard + derived
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandado(a))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'nombre_calle_inexistente',
        label: 'Nombre de la calle indicada (que no existe en la comuna)',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        order: 2,
        variable: 'nombre_calle_inexistente',
        text: 'Nombre de la calle indicada (que no existe en la comuna)',
        inputType: 'TEXT',
      },
    ],
  },
  {
    slug: 'busqueda_negativa_no_existe_calle_asi_mismo_informo',
    nombreVisible: 'No existe la calle en esta comuna + calle alternativa',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion: 'Búsqueda negativa cuando la calle indicada no existe en la comuna y se informa una calle alternativa que sí existe.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en la comuna de $solo_comuna_ejecutado,',
      '',
      'siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente, diligencia que no pude realizar, por cuanto, no existe la calle $nombre_calle_inexistente, en esta comuna. Así mismo informo que en esta comuna existe una calle llamada $nombre_calle_existente. En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      'Drs $monto_ejecutado',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandado(a))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'nombre_calle_inexistente',
        label: 'Nombre de la calle indicada (que no existe)',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      {
        name: 'nombre_calle_existente',
        label: 'Nombre de la calle alternativa que sí existe',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        order: 2,
        variable: 'nombre_calle_inexistente',
        text: 'Nombre de la calle indicada (que no existe)',
        inputType: 'TEXT',
      },
      {
        order: 3,
        variable: 'nombre_calle_existente',
        text: 'Nombre de la calle alternativa que sí existe',
        inputType: 'TEXT',
      },
    ],
  },
  {
    slug: 'busqueda_negativa_no_vive_en_ese_domicilio',
    nombreVisible: 'No vive en ese domicilio',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion: 'Búsqueda negativa cuando se informa que el demandado no vive en el domicilio indicado, incluyendo quién informó y si se identificó.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en el domicilio ubicado en $direccion_ejecutado,',
      '',
      'siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar',
      '',
      'a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente,',
      '',
      'diligencia que no pude efectuar por cuanto, $tratamiento_largo no vive en ese domicilio,',
      '',
      '$frase_persona_que_informa $frase_identificacion.',
      '',
      'En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      '',
      'Drs $monto_ejecutado',
      '',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      {
        name: 'direccion_ejecutado',
        label: 'Dirección del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'quien_informa',
        label: 'Quién informó',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'VECINA', label: 'Vecina' },
          { value: 'VECINO', label: 'Vecino' },
          { value: 'GUARDIA_CONDOMINIO', label: 'Guardia del condominio' },
          { value: 'CONSERJE_EDIFICIO', label: 'Conserje del edificio' },
          { value: 'ADULTO_MISMO_INMUEBLE', label: 'Persona adulta del mismo inmueble' },
        ],
      },
      {
        name: 'numero_vecino',
        label: 'Número de casa del vecino (opcional)',
        type: 'TEXT',
        source: 'USUARIO',
        required: false,
      },
      {
        name: 'se_identifico',
        label: '¿Se identificó?',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'SI', label: 'Sí' },
          { value: 'NO', label: 'No' },
        ],
      },
      {
        name: 'nombre_identificacion',
        label: 'Nombre con el que se identificó (opcional)',
        type: 'TEXT',
        source: 'USUARIO',
        required: false,
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandado(a))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'frase_persona_que_informa',
        label: 'Frase sobre quién informó',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['quien_informa', 'numero_vecino'],
      },
      {
        name: 'frase_identificacion',
        label: 'Frase sobre identificación',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['se_identifico', 'nombre_identificacion'],
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        order: 2,
        variable: 'quien_informa',
        text: 'Quién informó',
        inputType: 'SELECT',
        options: [
          { value: 'VECINA', label: 'Vecina' },
          { value: 'VECINO', label: 'Vecino' },
          { value: 'GUARDIA_CONDOMINIO', label: 'Guardia del condominio' },
          { value: 'CONSERJE_EDIFICIO', label: 'Conserje del edificio' },
          { value: 'ADULTO_MISMO_INMUEBLE', label: 'Persona adulta del mismo inmueble' },
        ],
      },
      {
        order: 3,
        variable: 'numero_vecino',
        text: 'Número de casa del vecino (opcional)',
        inputType: 'TEXT',
      },
      {
        order: 4,
        variable: 'se_identifico',
        text: '¿Se identificó?',
        inputType: 'RADIO',
        options: [
          { value: 'SI', label: 'Sí' },
          { value: 'NO', label: 'No' },
        ],
      },
      {
        order: 5,
        variable: 'nombre_identificacion',
        text: 'Nombre con el que se identificó (opcional)',
        inputType: 'TEXT',
      },
    ],
  },
  {
    slug: 'busqueda_negativa_no_fue_habido_no_es_persona_conocida',
    nombreVisible: 'No fue habido, no es persona conocida',
    categoria: 'BUSQUEDA_NEGATIVA',
    descripcion: 'Búsqueda negativa cuando el demandado no fue habido y consultados los vecinos no es persona conocida.',
    textoTemplate: [
      'CERTIFICO: Haberme constituido en el domicilio ubicado en $direccion_ejecutado,',
      '',
      'siendo las $hora_diligencia horas, para dar cumplimiento a la diligencia de notificar',
      '',
      'a $tratamiento_corto $nombre_ejecutado, la demanda y resolución precedente,',
      '',
      'diligencia que no pude efectuar por cuanto, $tratamiento_largo no fue habido,',
      '',
      'consultados los vecinos no es persona conocida.',
      '',
      'En $solo_comuna_ejecutado a $fecha_palabras_diligencia.-',
      '',
      '',
      'Drs $monto_ejecutado',
      '',
      '$firma',
    ].join('\n'),
    variablesSchema: [
      {
        name: 'direccion_ejecutado',
        label: 'Dirección del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'hora_diligencia',
        label: 'Hora de la diligencia',
        type: 'TIME',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'nombre_ejecutado',
        label: 'Nombre del ejecutado',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'solo_comuna_ejecutado',
        label: 'Comuna del domicilio',
        type: 'TEXT',
        source: 'ROL',
        required: true,
      },
      {
        name: 'fecha_palabras_diligencia',
        label: 'Fecha de la diligencia (en palabras)',
        type: 'TEXT',
        source: 'DILIGENCIA',
        required: true,
      },
      {
        name: 'monto_ejecutado',
        label: 'Monto adeudado',
        type: 'MONEY',
        source: 'ROL',
        required: false,
      },
      {
        name: 'firma',
        label: 'Firma del receptor',
        type: 'TEXT',
        source: 'USUARIO',
        required: true,
      },
      {
        name: 'sexo_demandado',
        label: 'Sexo del demandado',
        type: 'ENUM',
        source: 'USUARIO',
        required: true,
        enumOptions: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
      {
        name: 'tratamiento_corto',
        label: 'Tratamiento corto (don/doña/don(ña))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
      {
        name: 'tratamiento_largo',
        label: 'Tratamiento largo (el demandado/la demandada/el(la) demandado(a))',
        type: 'DERIVED',
        source: 'DERIVED',
        required: true,
        derivedFrom: ['sexo_demandado'],
      },
    ],
    wizardSchema: [
      {
        order: 1,
        variable: 'sexo_demandado',
        text: 'Sexo del demandado',
        inputType: 'RADIO',
        options: [
          { value: 'MASCULINO', label: 'Masculino' },
          { value: 'FEMENINO', label: 'Femenino' },
          { value: 'NO_DEFINIR', label: 'No definir' },
        ],
      },
    ],
  },
]

